version: '3'

services:
  #  flyway:
  #    image: boxfuse/flyway:5-alpine
  #    command: -url=jdbc:postgresql://postgres:5432/mydb -schemas=public -user=postgres -password=postgres
  #    volumes:
  #      - ./models:/flyway/sql
  #    depends_on:
  #      postgres:
  #        condition: service_healthy
  postgres-13:
    image: postgres:13
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "54313:5432"
    volumes:
      - postgres13:/var/lib/postgresql/data
    networks:
      - network

  postgres-14:
    image: postgres:14
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "54314:5432"
    volumes:
      - postgres14:/var/lib/postgresql/data
    networks:
      - network

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    volumes:
      - cloudbeaver-workspace:/opt/cloudbeaver/workspace
    ports:
      - "8181:8978"
    depends_on:
      - postgres-14
      - postgres-13
    networks:
      - network

volumes:
  postgres14:
  postgres13:
  cloudbeaver-workspace:

networks:
  network: